=== TWiStErRob/net.twisterrob.inventory/data.xml.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<!--suppress XmlDefaultAttributeValue -->
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

	<xsd:element name="inventory">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="property"    minOccurs="0" maxOccurs="unbounded" />
				<xsd:element ref="list"        minOccurs="0" maxOccurs="unbounded" />
			</xsd:sequence>
			<xsd:attribute name="version"          type="xsd:string"             use="optional">
				<xsd:annotation>
					<xsd:documentation>
						Version of the backup format.
						If omitted, inferred to be "1.0" for backwards compatibility.
					</xsd:documentation>
				</xsd:annotation>
			</xsd:attribute>
			<xsd:attribute name="approximateCount" type="xsd:nonNegativeInteger" use="optional" />
		</xsd:complexType>
		<!--region Identity listing-->
		<!-- unique/key/keyref xpaths are not full XPaths, just a subset:
		     https://www.w3.org/TR/2012/REC-xmlschema11-1-20120405/structures.html#c-selector-xpath -->
		<xsd:unique name="uniquePropertyID">
			<xsd:selector xpath=".//property" />
			<xsd:field xpath="@id" />
		</xsd:unique>
		<xsd:unique name="uniqueRoomID">
			<xsd:selector xpath=".//room" />
			<xsd:field xpath="@id" />
		</xsd:unique>
		<xsd:unique name="uniqueItemID">
			<xsd:selector xpath=".//item" />
			<xsd:field xpath="@id" />
		</xsd:unique>
		<xsd:key name="listItemKey">
			<xsd:selector xpath=".//item" />
			<xsd:field xpath="@id" />
		</xsd:key>
		<xsd:keyref name="listItemRef" refer="listItemKey">
			<xsd:selector xpath=".//item-ref" />
			<xsd:field xpath="@id" />
		</xsd:keyref>
		<!--endregion-->
	</xsd:element>

	<xsd:element name="property">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="description" minOccurs="0" maxOccurs="1" />
				<xsd:element ref="room"        minOccurs="0" maxOccurs="unbounded" />
			</xsd:sequence>
			<xsd:attribute name="id"    type="xsd:nonNegativeInteger" use="required" />
			<xsd:attribute name="name"  type="xsd:string"             use="required" />
			<xsd:attribute name="type"  type="xsd:string"             use="required" />
			<xsd:attribute name="image" type="imagePath"              use="optional" />
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="room">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="description" minOccurs="0" maxOccurs="1" />
				<xsd:element ref="item"        minOccurs="0" maxOccurs="unbounded" />
			</xsd:sequence>
			<xsd:attribute name="id"    type="xsd:nonNegativeInteger" use="required" />
			<xsd:attribute name="name"  type="xsd:string"             use="required" />
			<xsd:attribute name="type"  type="xsd:string"             use="required" />
			<xsd:attribute name="image" type="imagePath"              use="optional" />
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="item">
		<xsd:annotation>
			<xsd:documentation>
				Represents an item in the inventory, it is recursively nestable.
			</xsd:documentation>
		</xsd:annotation>
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="description" minOccurs="0" maxOccurs="1" />
				<xsd:element ref="item"        minOccurs="0" maxOccurs="unbounded" />
			</xsd:sequence>
			<xsd:attribute name="id"    type="xsd:nonNegativeInteger" use="required" />
			<xsd:attribute name="name"  type="xsd:string"             use="required" />
			<xsd:attribute name="type"  type="xsd:string"             use="required" />
			<xsd:attribute name="image" type="imagePath"              use="optional" />
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="list">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="item-ref"    minOccurs="0" maxOccurs="unbounded" />
			</xsd:sequence>
			<xsd:attribute name="name"  type="xsd:string"             use="required" />
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="item-ref">
		<xsd:complexType>
			<xsd:sequence />
			<xsd:attribute name="id"    type="xsd:nonNegativeInteger" use="required" />
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="description">
		<xsd:simpleType>
			<xsd:restriction base="xsd:string" />
		</xsd:simpleType>
	</xsd:element>

	<xsd:simpleType name="imagePath">
		<xsd:annotation>
			<xsd:documentation>
				Location of the image file relative to data.xml (inside the backup ZIP).
			</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base="xsd:string" />
	</xsd:simpleType>

</xsd:schema>

=== TWiStErRob/net.twisterrob.inventory/android/backup/src/main/assets/demo.xml
<?xml version='1.0' encoding='utf-8' standalone='yes' ?>
<?xml-stylesheet type="text/xsl" href="data.html.xslt"?>
<!-- An up to date version of the XSD Schema can be found at
     https://github.com/TWiStErRob/net.twisterrob.inventory -->
<inventory approximateCount="34" version="1.0"
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xsi:noNamespaceSchemaLocation="data.xml.xsd"
	>
	<property type="property_house" name="Home" id="1">
		<room type="room_bed" name="My room" id="1">
			<item type="category_lounging" name="Double Bed" id="2" />
			<item type="category_surface_flat" name="Study Desk" id="3">
				<item type="category_compartment" name="Desktop" id="4">
					<item type="category_lighting" name="Desk Lamp" id="5" />
					<item type="category_computer_portable" name="Laptop" id="6" />
				</item>
				<item type="category_compartment" name="Drawer" id="7" />
			</item>
			<item type="category_seating" name="Chair" id="8" />
		</room>
		<room type="room_dining" name="Kitchen" id="2">
			<item type="category_appliance_storage" name="Fridge" id="10" />
			<item type="category_cabinetry" name="Base Cabinet" id="11">
				<item type="category_compartment" name="Left Drawer" id="12">
					<item type="category_cutlery" name="Dessert Spoon x2" id="13" />
					<item type="category_cutlery" name="Stainless Steel Knife x2" id="14" />
					<item type="category_cutlery" name="Plastic Fork x10" id="15" />
				</item>
				<item type="category_compartment" name="Right Drawer" id="16">
					<item type="category_utensil_chop" name="Peeler" id="17" />
					<item type="category_utensil_open" name="Can Opener" id="18" />
				</item>
			</item>
			<item type="category_group" name="Dining Area" id="19">
				<item type="category_seating" name="Chair x3" id="20" />
				<item type="category_surface_flat" name="Table" id="21" />
			</item>
			<item type="category_fixture_wet" name="Sink" id="29">
				<item type="category_cleaning_wet" name="Yellow Kitchen Sponge" id="30" />
			</item>
		</room>
		<room type="room_bath" name="Bathroom" id="3">
			<item type="category_fixture_wet" name="Sink" id="23">
				<item type="category_hygiene_body" name="Silky Smooth Soap" id="31" />
			</item>
			<item type="category_cabinetry" name="Mirror Cabinet" id="24">
				<item type="category_hygiene_oral" name="Toothbrush" id="25" />
				<item type="category_cosmetic_trim" name="Shaving Razor" id="26" />
			</item>
			<item type="category_fixture_wet" name="Bathtub" id="27">
				<item type="category_hygiene_body" name="Shower Gel" id="32" />
				<item type="category_hygiene_body" name="Anti-Dandruff Shampoo" id="33" />
			</item>
			<item type="category_fixture_wet" name="Toilet" id="28" />
		</room>
	</property>
	<list name="Travel Items">
		<item-ref id="6" /><!--Laptop-->
		<item-ref id="25" /><!--Toothbrush-->
	</list>
</inventory>
